### ISSUE TITLE
crazy

### ISSUE THREAD

**Issue by imvast** [RootnuII/RootnuII#1]
what a fire readme tbh but no credits is kinda sad

**Comment by RootnuII** [comment]
bahahah my bad man

**Comment by RootnuII** [comment]
dont act like its that good tho i know there's other readme's that are fire

**Comment by imvast** [comment]
someones ego is getting in the way, crazy how its been 4 months and youve still yet to even change it 😭 so sad, skids gon be skids

**Comment by RootnuII** [comment]
crazy how its just a templet for GitHub

**Comment by imvast** [comment]
> crazy how its just a templet for GitHub

crazy how even if it was, which it's not, it doesn't change the fact that you completely copy and pasted my shit 🤡

**Comment by RootnuII** [comment]
copy and pasted a readme 😭 your full of yourself my guy

**Comment by RootnuII** [comment]
copy and pasted i literally forked it cuz its open source
